# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-05-22 02:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Keyword',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('weight', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic_number', models.IntegerField()),
                ('corpus_number', models.IntegerField()),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TopicUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField(unique=True)),
                ('topic_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_topic', to='topic.Topic')),
            ],
        ),
        migrations.AddField(
            model_name='keyword',
            name='topic_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='keyword_topic', to='topic.Topic'),
        ),
    ]
