# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-05-24 20:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('TMengine', '0002_auto_20180524_2029'),
        ('topic', '0003_auto_20180523_0303'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='topic',
            name='corpus_number',
        ),
        migrations.AddField(
            model_name='topic',
            name='lda_model',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topic_ldamodel', to='TMengine.LdaModel'),
            preserve_default=False,
        ),
    ]
