# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-07-08 03:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='New',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_date', models.DateField(auto_now=True)),
                ('publication_date', models.DateField(null=True)),
                ('title', models.CharField(max_length=1000)),
                ('description', models.TextField(null=True)),
                ('full_text', models.TextField(null=True)),
                ('info_source', models.TextField(null=True)),
                ('image_source', models.TextField(null=True)),
            ],
        ),
    ]
