# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-07-17 02:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('new', '0002_new_used_to_classify'),
    ]

    operations = [
        migrations.RenameField(
            model_name='new',
            old_name='description',
            new_name='main_image',
        ),
        migrations.RenameField(
            model_name='new',
            old_name='publication_date',
            new_name='published',
        ),
        migrations.RenameField(
            model_name='new',
            old_name='full_text',
            new_name='site',
        ),
        migrations.RenameField(
            model_name='new',
            old_name='image_source',
            new_name='site_name',
        ),
        migrations.RenameField(
            model_name='new',
            old_name='info_source',
            new_name='text',
        ),
        migrations.AddField(
            model_name='new',
            name='url',
            field=models.TextField(null=True),
        ),
    ]
