# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-07-23 15:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('topic', '0004_auto_20180524_2029'),
        ('new', '0003_auto_20180717_0236'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewClassification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('classification', models.FloatField()),
                ('new_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='new_classification', to='new.New')),
                ('topic_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topic_new', to='topic.Topic')),
            ],
        ),
    ]
