# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-05-24 05:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LdaModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1000, unique=True)),
                ('creation_date', models.DateField(auto_now=True)),
                ('newest', models.BooleanField(default=True)),
                ('in_use', models.BooleanField()),
            ],
        ),
    ]
