# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-07-17 02:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TMengine', '0002_auto_20180524_2029'),
    ]

    operations = [
        migrations.AddField(
            model_name='ldamodel',
            name='in_use',
            field=models.BooleanField(default=False),
        ),
    ]
