# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-09-25 22:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TMengine', '0003_ldamodel_in_use'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrainingStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_training', models.BooleanField(default=False)),
            ],
        ),
    ]
